name: send nudes

on: push

jobs:
  basic-usage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hustcer/setup-nu@v3.9
        with:
          version: "0.87"
      - name: list content
        run: ls
      - name: run example nu-shell script
        run: nu example.nu 
        env:
          GRIST_APIKEY: ${{ secrets.GRIST_APIKEY }}
          GRIST_DOC: ${{ secrets.GRIST_DOC }}
          GRIST_DOMAIN: ${{ secrets.GRIST_DOMAIN }}
          GRIST_ORG: ${{ secrets.GRIST_ORG }}
          GRIST_WORKSPACE: ${{ secrets.GRIST_WORKSPACE }}

