name: send nudes

on: push
defaults:
  run:
    shell: nu {0}

- uses: hustcer/setup-nu@v3.9
  with:
    version: "0.87" 

- env:
    GRIST_APIKEY: ${{ secrets.GRIST_APIKEY }}
    GRIST_DOC: ${{ secrets.GRIST_DOC }}
    GRIST_DOMAIN: ${{ secrets.GRIST_DOMAIN }}
    GRIST_ORG: ${{ secrets.GRIST_ORG }}
    GRIST_WORKSPACE: ${{ secrets.GRIST_WORKSPACE }}

- name: run example nu-shell script
  run: ./example.nu 

